In [2]:
import pandas as pd
df = pd.read_csv(r"C:\Users\opiyo\Documents\Datasets\DataBreaches.csv")
df.head()

,Entity,Year,Records,Organization type,Method
0,21st Century Oncology,2016,2200000,healthcare,hacked
1,500px,2020,14870304,social networking,hacked
2,Accendo Insurance Co.,2020,175350,healthcare,poor security
3,Adobe Systems Incorporated,2013,152000000,tech,hacked
4,Adobe Inc.,2019,7500000,tech,poor security

In [4]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 295 entries, 0 to 294
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Entity             295 non-null    object
 1   Year               295 non-null    object
 2   Records            295 non-null    int64
 3   Organization type  295 non-null    object
 4   Method             295 non-null    object
dtypes: int64(1), object(4)
memory usage: 11.7+ KB

Entity               0
Year                 0
Records              0
Organization type    0
Method               0
dtype: int64

In [6]:
df['Year'].unique()

array(['2016', '2020', '2013', '2019', '2017', '2018', '2005', '2021',
       '2014', '2015', '2008', '2010', '2009', '2011', '2012', '2007',
       '2006', '2018-2019', '2014 and 2015', '2004'], dtype=object)

In [7]:
df[df['Year'].isin(['2018-2019', '2014 and 2015'])]

,Entity,Year,Records,Organization type,Method
78,"Earl Enterprises(Buca di Beppo, Earl of Sandwi...",2018-2019,2000000,restaurant,hacked
120,Hilton Hotels,2014 and 2015,363000,hotel,hacked

In [9]:
df['Year'] = df['Year'].replace({
    '2018-2019': '2018',
    '2014 and 2015': '2014'
})
df['Year'] = df['Year'].astype(int)

In [10]:
df['Year'].dtype

dtype('int64')